openapi: 3.0.0
info:
  title: Exemple d'API Utilisateurs et Livres
  version: 1.0.0
  description: Une API de démonstration pour gérer des utilisateurs et des livres.
servers:
  - url: http://localhost:3000
    description: Serveur de développement

paths:
  /api/users:
    get:
      summary: Récupérer la liste des utilisateurs
      responses:
        '200':
          description: Réponse réussie
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string

    post:
      summary: Ajouter un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Utilisateur ajouté avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string

  /api/books:
    get:
      summary: Récupérer la liste des livres
      responses:
        '200':
          description: Réponse réussie
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string

    post:
      summary: Ajouter un livre
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '201':
          description: Livre ajouté avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
